version: "3.9"

services:
  db:                     
    image: postgres:16      
    container_name: samgestor-db
    environment:            
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"         
    volumes:
      - postgres-data:/var/lib/postgresql/data   

  pgadmin:                  
    image: dpage/pgadmin4:8
    container_name: samgestor-pgadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"           

volumes:
  postgres-data:            
