// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SAMGestor.Infrastructure.Persistence;

#nullable disable

namespace SAMGestor.Infrastructure.Migrations
{
    [DbContext(typeof(SAMContext))]
    [Migration("20251207203557_FixTentNumberType")]
    partial class FixTentNumberType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SAMGestor.Domain.Entities.BlockedCpf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("blocked_cpfs", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.ChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_name");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("change_logs", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.EmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TokenHash")
                        .IsUnique();

                    b.ToTable("email_confirmation_tokens", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("GroupChannel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("group_channel");

                    b.Property<DateTimeOffset?>("GroupCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("group_created_at");

                    b.Property<string>("GroupExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("group_external_id");

                    b.Property<DateTimeOffset?>("GroupLastNotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("group_last_notified_at");

                    b.Property<string>("GroupLink")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("group_link");

                    b.Property<int>("GroupStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("group_status");

                    b.Property<int>("GroupVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("group_version");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("RetreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("retreat_id");

                    b.HasKey("Id");

                    b.HasIndex("RetreatId");

                    b.HasIndex("RetreatId", "GroupStatus");

                    b.HasIndex("RetreatId", "Name")
                        .IsUnique();

                    b.ToTable("families", "core", t =>
                        {
                            t.HasCheckConstraint("ck_families_capacity_positive", "capacity > 0");
                        });
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<Guid>("RetreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("retreat_id");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("FamilyId", "Position")
                        .IsUnique();

                    b.HasIndex("FamilyId", "RegistrationId")
                        .IsUnique();

                    b.HasIndex("RetreatId", "FamilyId");

                    b.HasIndex("RetreatId", "RegistrationId")
                        .IsUnique();

                    b.ToTable("family_members", "core", t =>
                        {
                            t.HasCheckConstraint("ck_family_members_position_nonneg", "position >= 0");
                        });
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.MessageSent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_template_id");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("messages_sent", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<bool>("HasPlaceholders")
                        .HasColumnType("boolean")
                        .HasColumnName("has_placeholders");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("message_templates", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TokenHash")
                        .IsUnique();

                    b.ToTable("password_reset_tokens", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("payments", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TokenHash")
                        .IsUnique();

                    b.ToTable("refresh_tokens", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.RegionConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Observation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observation");

                    b.Property<Guid>("RetreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("retreat_id");

                    b.HasKey("Id");

                    b.HasIndex("RetreatId", "Name")
                        .IsUnique();

                    b.ToTable("region_configs", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlcoholUse")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("None")
                        .HasColumnName("alcohol_use");

                    b.Property<string>("AllergiesDetails")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("allergies_details");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("client_ip");

                    b.Property<bool>("CompletedRetreat")
                        .HasColumnType("boolean")
                        .HasColumnName("completed_retreat");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("DrugUseFrequency")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("drug_use_frequency");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FacebookUsername")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("facebook_username");

                    b.Property<string>("FamilyLossDetails")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("family_loss_details");

                    b.Property<string>("FatherName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("father_name");

                    b.Property<string>("FatherPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("father_phone");

                    b.Property<string>("FatherStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("father_status");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool?>("HadFamilyLossLast6Months")
                        .IsRequired()
                        .HasColumnType("boolean")
                        .HasColumnName("had_family_loss_last6m");

                    b.Property<bool?>("HasAllergies")
                        .IsRequired()
                        .HasColumnType("boolean")
                        .HasColumnName("has_allergies");

                    b.Property<bool?>("HasMedicalRestriction")
                        .IsRequired()
                        .HasColumnType("boolean")
                        .HasColumnName("has_medical_restriction");

                    b.Property<bool?>("HasRelativeOrFriendSubmitted")
                        .IsRequired()
                        .HasColumnType("boolean")
                        .HasColumnName("has_relative_or_friend_submitted");

                    b.Property<decimal?>("HeightCm")
                        .IsRequired()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("IdDocumentContentType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("id_document_content_type");

                    b.Property<string>("IdDocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_document_number");

                    b.Property<int?>("IdDocumentSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("id_document_size_bytes");

                    b.Property<string>("IdDocumentStorageKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("id_document_storage_key");

                    b.Property<string>("IdDocumentType")
                        .HasColumnType("text")
                        .HasColumnName("id_document_type");

                    b.Property<DateTime?>("IdDocumentUploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("id_document_uploaded_at");

                    b.Property<string>("InstagramHandle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("instagram_handle");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marital_status");

                    b.Property<bool>("MarketingOptIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("marketing_opt_in");

                    b.Property<DateTime?>("MarketingOptInAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("marketing_opt_in_at");

                    b.Property<string>("MedicalRestrictionDetails")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("medical_restriction_details");

                    b.Property<string>("MedicationsDetails")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("medications_details");

                    b.Property<string>("MotherName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("mother_name");

                    b.Property<string>("MotherPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mother_phone");

                    b.Property<string>("MotherStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mother_status");

                    b.Property<string>("NeighborPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("neighbor_phone");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("neighborhood");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("photo_content_type");

                    b.Property<int?>("PhotoSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("photo_size_bytes");

                    b.Property<string>("PhotoStorageKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("photo_storage_key");

                    b.Property<DateTime?>("PhotoUploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("photo_uploaded_at");

                    b.Property<string>("PhysicalLimitationDetails")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("physical_limitation_details");

                    b.Property<string>("Pregnancy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("None")
                        .HasColumnName("pregnancy");

                    b.Property<string>("PreviousUncalledApplications")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("None")
                        .HasColumnName("prev_uncalled_applications");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("profession");

                    b.Property<string>("RahaminVidaCompleted")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("None")
                        .HasColumnName("rahamin_vida_completed");

                    b.Property<string>("RecentSurgeryOrProcedureDetails")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("recent_surgery_or_procedure_details");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<string>("RelativePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("relative_phone");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("religion");

                    b.Property<Guid>("RetreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("retreat_id");

                    b.Property<string>("ShirtSize")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shirt_size");

                    b.Property<bool?>("Smoker")
                        .IsRequired()
                        .HasColumnType("boolean")
                        .HasColumnName("smoker");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StreetAndNumber")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("street_and_number");

                    b.Property<string>("SubmitterNames")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("submitter_names");

                    b.Property<string>("SubmitterRelationship")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("None")
                        .HasColumnName("submitter_relationship");

                    b.Property<bool?>("TakesMedication")
                        .IsRequired()
                        .HasColumnType("boolean")
                        .HasColumnName("takes_medication");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid?>("TentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tent_id");

                    b.Property<bool>("TermsAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("terms_accepted");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terms_accepted_at");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("terms_version");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<bool?>("UsesDrugs")
                        .IsRequired()
                        .HasColumnType("boolean")
                        .HasColumnName("uses_drugs");

                    b.Property<decimal?>("WeightKg")
                        .IsRequired()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasIndex("Cpf");

                    b.HasIndex("Email");

                    b.HasIndex("RetreatId", "Cpf")
                        .IsUnique();

                    b.HasIndex("RetreatId", "Email")
                        .IsUnique();

                    b.HasIndex("RetreatId", "Status", "Gender");

                    b.ToTable("registrations", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_creation");

                    b.Property<string>("DefaultParamsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("default_params_json");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.Property<Guid?>("RetreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("retreat_id");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("template_key");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("DateCreation")
                        .HasDatabaseName("ix_reports_date_creation");

                    b.HasIndex("RetreatId", "TemplateKey")
                        .HasDatabaseName("ix_reports_retreat_template");

                    b.ToTable("reports", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.ReportInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("format");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("storage_path");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "GeneratedAt")
                        .HasDatabaseName("ix_report_instances_report_date");

                    b.ToTable("report_instances", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Retreat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ContemplationClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("contemplation_closed");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("edition");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("FamiliesLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("families_locked");

                    b.Property<int>("FamiliesVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("families_version");

                    b.Property<int>("FemaleSlots")
                        .HasColumnType("integer")
                        .HasColumnName("female_slots");

                    b.Property<int>("MaleSlots")
                        .HasColumnType("integer")
                        .HasColumnName("male_slots");

                    b.Property<string>("PrivacyPolicyBody")
                        .HasColumnType("text");

                    b.Property<string>("PrivacyPolicyTitle")
                        .HasColumnType("text");

                    b.Property<string>("PrivacyPolicyVersion")
                        .HasColumnType("text");

                    b.Property<DateOnly>("RegistrationEnd")
                        .HasColumnType("date")
                        .HasColumnName("registration_end");

                    b.Property<DateOnly>("RegistrationStart")
                        .HasColumnType("date")
                        .HasColumnName("registration_start");

                    b.Property<bool>("ServiceLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("service_locked");

                    b.Property<int>("ServiceSpacesVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("service_spaces_version");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<bool>("TentsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tents_locked");

                    b.Property<int>("TentsVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tents_version");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("theme");

                    b.HasKey("Id");

                    b.ToTable("retreats", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.ServiceAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("ServiceRegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_registration_id");

                    b.Property<Guid>("ServiceSpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_space_id");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRegistrationId")
                        .IsUnique();

                    b.HasIndex("ServiceSpaceId")
                        .IsUnique()
                        .HasDatabaseName("UX_service_assignments_one_vice_per_space")
                        .HasFilter("role = 2");

                    b.HasIndex("ServiceSpaceId", "Role");

                    b.ToTable("service_assignments", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.ServiceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<Guid?>("PreferredSpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_space_id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("region");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<Guid>("RetreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("retreat_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Cpf");

                    b.HasIndex("Email");

                    b.HasIndex("PreferredSpaceId");

                    b.HasIndex("RetreatId", "Cpf")
                        .IsUnique();

                    b.HasIndex("RetreatId", "Email")
                        .IsUnique();

                    b.HasIndex("RetreatId", "Status");

                    b.ToTable("service_registrations", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.ServiceRegistrationPayment", b =>
                {
                    b.Property<Guid>("ServiceRegistrationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServiceRegistrationId", "PaymentId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("service_registration_payments", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.ServiceSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxPeople")
                        .HasColumnType("integer");

                    b.Property<int>("MinPeople")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RetreatId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RetreatId", "IsActive");

                    b.HasIndex("RetreatId", "Name")
                        .IsUnique();

                    b.ToTable("service_spaces", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int>("MemberLimit")
                        .HasColumnType("integer")
                        .HasColumnName("member_limit");

                    b.Property<int>("MinMembers")
                        .HasColumnType("integer")
                        .HasColumnName("min_members");

                    b.Property<Guid>("RetreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("retreat_id");

                    b.HasKey("Id");

                    b.ToTable("teams", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "RegistrationId")
                        .IsUnique();

                    b.ToTable("team_members", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Tent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("category");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<string>("Notes")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("notes");

                    b.Property<Guid>("RetreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("retreat_id");

                    b.HasKey("Id");

                    b.HasIndex("RetreatId");

                    b.ToTable("tents", "core", t =>
                        {
                            t.HasCheckConstraint("ck_tents_capacity_positive", "capacity > 0");
                        });
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.TentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<int?>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<Guid>("TentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tent_id");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique()
                        .HasDatabaseName("ux_tent_assignments_registration");

                    b.HasIndex("TentId");

                    b.ToTable("tent_assignments", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTimeOffset?>("EmailConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_confirmed_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("FailedAccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_access_count");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_at");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.WaitingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<Guid>("RetreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("retreat_id");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.HasIndex("RetreatId", "Position")
                        .IsUnique();

                    b.ToTable("waiting_list_items", "core");
                });

            modelBuilder.Entity("SAMGestor.Infrastructure.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_processed");

                    b.HasIndex("Type", "CreatedAt")
                        .HasDatabaseName("ix_outbox_type_created");

                    b.ToTable("outbox_messages", "core");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.EmailConfirmationToken", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.User", "User")
                        .WithMany("EmailConfirmationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Family", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.Retreat", null)
                        .WithMany()
                        .HasForeignKey("RetreatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.Family", null)
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAMGestor.Domain.Entities.Registration", null)
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Payment", b =>
                {
                    b.OwnsOne("SAMGestor.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments", "core");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.RegionConfig", b =>
                {
                    b.OwnsOne("SAMGestor.Domain.ValueObjects.Percentage", "TargetPercentage", b1 =>
                        {
                            b1.Property<Guid>("RegionConfigId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("target_percentage");

                            b1.HasKey("RegionConfigId");

                            b1.ToTable("region_configs", "core");

                            b1.WithOwner()
                                .HasForeignKey("RegionConfigId");
                        });

                    b.Navigation("TargetPercentage")
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Registration", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.Retreat", null)
                        .WithMany()
                        .HasForeignKey("RetreatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SAMGestor.Domain.ValueObjects.UrlAddress", "IdDocumentUrl", b1 =>
                        {
                            b1.Property<Guid>("RegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("id_document_url");

                            b1.HasKey("RegistrationId");

                            b1.ToTable("registrations", "core");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.OwnsOne("FullName", "Name", b1 =>
                        {
                            b1.Property<Guid>("RegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("RegistrationId");

                            b1.ToTable("registrations", "core");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.OwnsOne("SAMGestor.Domain.ValueObjects.UrlAddress", "PhotoUrl", b1 =>
                        {
                            b1.Property<Guid>("RegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("photo_url");

                            b1.HasKey("RegistrationId");

                            b1.ToTable("registrations", "core");

                            b1.WithOwner()
                                .HasForeignKey("RegistrationId");
                        });

                    b.Navigation("IdDocumentUrl");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PhotoUrl");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Report", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.Retreat", null)
                        .WithMany()
                        .HasForeignKey("RetreatId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.ReportInstance", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Retreat", b =>
                {
                    b.OwnsOne("SAMGestor.Domain.ValueObjects.Money", "FeeFazer", b1 =>
                        {
                            b1.Property<Guid>("RetreatId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("fee_fazer_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("fee_fazer_currency");

                            b1.HasKey("RetreatId");

                            b1.ToTable("retreats", "core");

                            b1.WithOwner()
                                .HasForeignKey("RetreatId");
                        });

                    b.OwnsOne("SAMGestor.Domain.ValueObjects.Money", "FeeServir", b1 =>
                        {
                            b1.Property<Guid>("RetreatId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("fee_servir_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("fee_servir_currency");

                            b1.HasKey("RetreatId");

                            b1.ToTable("retreats", "core");

                            b1.WithOwner()
                                .HasForeignKey("RetreatId");
                        });

                    b.OwnsOne("FullName", "Name", b1 =>
                        {
                            b1.Property<Guid>("RetreatId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("RetreatId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("retreats", "core");

                            b1.WithOwner()
                                .HasForeignKey("RetreatId");
                        });

                    b.OwnsOne("SAMGestor.Domain.ValueObjects.Percentage", "OtherRegionsPercentage", b1 =>
                        {
                            b1.Property<Guid>("RetreatId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("other_regions_pct");

                            b1.HasKey("RetreatId");

                            b1.ToTable("retreats", "core");

                            b1.WithOwner()
                                .HasForeignKey("RetreatId");
                        });

                    b.OwnsOne("SAMGestor.Domain.ValueObjects.Percentage", "WestRegionPercentage", b1 =>
                        {
                            b1.Property<Guid>("RetreatId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("west_region_pct");

                            b1.HasKey("RetreatId");

                            b1.ToTable("retreats", "core");

                            b1.WithOwner()
                                .HasForeignKey("RetreatId");
                        });

                    b.Navigation("FeeFazer")
                        .IsRequired();

                    b.Navigation("FeeServir")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("OtherRegionsPercentage")
                        .IsRequired();

                    b.Navigation("WestRegionPercentage")
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.ServiceAssignment", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.ServiceRegistration", null)
                        .WithMany()
                        .HasForeignKey("ServiceRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAMGestor.Domain.Entities.ServiceSpace", null)
                        .WithMany()
                        .HasForeignKey("ServiceSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.ServiceRegistration", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.ServiceSpace", null)
                        .WithMany()
                        .HasForeignKey("PreferredSpaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SAMGestor.Domain.Entities.Retreat", null)
                        .WithMany()
                        .HasForeignKey("RetreatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FullName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ServiceRegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("full_name");

                            b1.HasKey("ServiceRegistrationId");

                            b1.ToTable("service_registrations", "core");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRegistrationId");
                        });

                    b.OwnsOne("SAMGestor.Domain.ValueObjects.UrlAddress", "PhotoUrl", b1 =>
                        {
                            b1.Property<Guid>("ServiceRegistrationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("photo_url");

                            b1.HasKey("ServiceRegistrationId");

                            b1.ToTable("service_registrations", "core");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRegistrationId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PhotoUrl");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.ServiceRegistrationPayment", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SAMGestor.Domain.Entities.ServiceRegistration", null)
                        .WithMany()
                        .HasForeignKey("ServiceRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Team", b =>
                {
                    b.OwnsOne("FullName", "Name", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("TeamId");

                            b1.ToTable("teams", "core");

                            b1.WithOwner()
                                .HasForeignKey("TeamId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.Team", null)
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Tent", b =>
                {
                    b.OwnsOne("SAMGestor.Domain.ValueObjects.TentNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("TentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("number");

                            b1.HasKey("TentId");

                            b1.ToTable("tents", "core");

                            b1.WithOwner()
                                .HasForeignKey("TentId");
                        });

                    b.Navigation("Number")
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.TentAssignment", b =>
                {
                    b.HasOne("SAMGestor.Domain.Entities.Registration", null)
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAMGestor.Domain.Entities.Tent", null)
                        .WithMany()
                        .HasForeignKey("TentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.User", b =>
                {
                    b.OwnsOne("FullName", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("name");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "core");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("SAMGestor.Domain.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users", "core");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("SAMGestor.Domain.ValueObjects.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "core");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Family", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SAMGestor.Domain.Entities.User", b =>
                {
                    b.Navigation("EmailConfirmationTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
